package common.nw.installer.gui;

import common.nw.gui.PageHolder;
import common.nw.installer.PrepackedInstall;
import common.nw.utils.log.NwLogger;

import javax.swing.*;
import java.awt.*;

/**
 * @author Nuklearwurst
 */
public class InstallerWindow {

	/**
	 * Main Window
	 */
	private JFrame window;
	/////////////////////////////////////////
	// Button Panel and other gui elements //
	/////////////////////////////////////////
	private JButton btnBack;
	private JPanel content_panel;
	private JButton btnNext;
	private JButton btnCancel;
	private JPanel card_panel;
	private JPanel btn_panel;
	/**
	 * Page Holder
	 */
	private PageHolder pageHolder;

	public InstallerWindow() {
		this(false);
	}

	public InstallerWindow(boolean preset) {
		this(preset ? PrepackedInstall.MODPACK_URL : null);
	}

	public InstallerWindow(String url) {
		//Initialize UI
		window = new JFrame("Installer Window");
		$$$setupUI$$$();
		window.setBounds(100, 100, 450, 300);
		window.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
		window.setContentPane(content_panel);

		if (url != null) {
			pageHolder.nextPage();
		}
	}


	private void createUIComponents() {
		pageHolder = new PageHolder();
		card_panel = pageHolder.getPanel();
	}

	// Main entry point
	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				// look and feel
				try {
					UIManager.setLookAndFeel(UIManager
							.getSystemLookAndFeelClassName());
				} catch (Throwable t) {
					NwLogger.INSTALLER_LOGGER.error("Error when setting Look and Feel!", t);
				}
				try {
					InstallerWindow window = new InstallerWindow();
					window.window.pack();
					window.window.setVisible(true);
				} catch (Exception e) {
					NwLogger.INSTALLER_LOGGER.error("Error when starting GUI!", e);
				}
			}
		});
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		createUIComponents();
		content_panel = new JPanel();
		content_panel.setLayout(new BorderLayout(0, 0));
		btn_panel = new JPanel();
		btn_panel.setLayout(new FlowLayout(FlowLayout.RIGHT, 5, 5));
		content_panel.add(btn_panel, BorderLayout.SOUTH);
		btnBack = new JButton();
		btnBack.setText("Back");
		btn_panel.add(btnBack);
		btnNext = new JButton();
		btnNext.setText("Next");
		btn_panel.add(btnNext);
		btnCancel = new JButton();
		btnCancel.setText("Cancel");
		btn_panel.add(btnCancel);
		content_panel.add(card_panel, BorderLayout.CENTER);
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return content_panel;
	}
}
