package common.nw.installer.gui;

import common.nw.gui.IPageHandler;
import common.nw.gui.PageHolder;

import javax.swing.*;
import java.awt.*;

/**
 * @author Nuklearwurst
 */
public class PanelInit implements IPageHandler {
	private JTextPane txtInit;
	private JTextField textField1;
	private JCheckBox chbxDonwloadLibraries;
	private JPanel panel_init;

	public PanelInit() {
		txtInit.setBackground(SystemColor.menu);
	}

	@Override
	public Object getProperty(String s) {
		return null;
	}

	@Override
	public void onPageOpened(PageHolder holder, boolean forward) {

	}

	@Override
	public boolean onPageClosed(PageHolder holder, boolean forward) {
		return false;
	}

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		panel_init = new JPanel();
		panel_init.setLayout(new GridBagLayout());
		txtInit = new JTextPane();
		txtInit.setContentType("text/html");
		txtInit.setEditable(false);
		txtInit.setFont(new Font(txtInit.getFont().getName(), Font.BOLD, txtInit.getFont().getSize()));
		txtInit.setText("<html>\r\n  <head>\r\n    \r\n  </head>\r\n  <body>\r\n    <p style=\"margin-top: 0\">\r\n      <b>Welcome to The Modpack Installer<br>This installer will guide you \r\n      through the modpack installation process.<br><br>Now insert the modpack \r\n      Url: </b>\r\n    </p>\r\n  </body>\r\n</html>\r\n");
		GridBagConstraints gbc;
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 0;
		gbc.gridwidth = 2;
		gbc.weightx = 1.0;
		gbc.fill = GridBagConstraints.BOTH;
		panel_init.add(txtInit, gbc);
		final JPanel spacer1 = new JPanel();
		gbc = new GridBagConstraints();
		gbc.gridx = 2;
		gbc.gridy = 0;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		panel_init.add(spacer1, gbc);
		final JPanel spacer2 = new JPanel();
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 3;
		gbc.gridwidth = 2;
		gbc.weighty = 1.0;
		gbc.fill = GridBagConstraints.VERTICAL;
		panel_init.add(spacer2, gbc);
		final JLabel label1 = new JLabel();
		label1.setText("Modpack Url:");
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 1;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.insets = new Insets(0, 0, 0, 4);
		panel_init.add(label1, gbc);
		textField1 = new JTextField();
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 1;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		panel_init.add(textField1, gbc);
		chbxDonwloadLibraries = new JCheckBox();
		chbxDonwloadLibraries.setSelected(true);
		chbxDonwloadLibraries.setText("Download supported Libraries (recommended)");
		chbxDonwloadLibraries.setToolTipText("You should download supported libraries using the installer. Otherwise you have to do it manually.");
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 2;
		gbc.gridwidth = 2;
		gbc.anchor = GridBagConstraints.WEST;
		panel_init.add(chbxDonwloadLibraries, gbc);
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return panel_init;
	}
}
