package common.nw.installer.gui;


import common.nw.core.gui.IExtendedPageHandler;
import common.nw.core.gui.PageHolder;

import javax.swing.*;
import javax.swing.event.HyperlinkEvent;
import javax.swing.event.HyperlinkListener;
import java.awt.*;
import java.io.IOException;
import java.net.URISyntaxException;

/**
 * @author Nuklearwurst
 */
public class PanelOverview implements IExtendedPageHandler {
	private JPanel panel_overview;
	protected JEditorPane txtpnModpackInfo;

	public PanelOverview() {
		txtpnModpackInfo.addHyperlinkListener(new HyperlinkListener() {
			@Override
			public void hyperlinkUpdate(HyperlinkEvent e) {
				if (e.getEventType() == HyperlinkEvent.EventType.ACTIVATED) {
					if (Desktop.isDesktopSupported()) {
						try {
							Desktop.getDesktop().browse(e.getURL().toURI());
						} catch (IOException | URISyntaxException e1) {
							e1.printStackTrace();
						}
					}
				}
			}
		});
	}


	@Override
	public Object getProperty(String s) {
		return null;
	}

	@Override
	public void onPageOpened(PageHolder holder, boolean forward) {

	}

	@Override
	public boolean onPageClosed(PageHolder holder, boolean forward) {
		return true;
	}

	@Override
	public JPanel getPanel() {
		return panel_overview;
	}

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		panel_overview = new JPanel();
		panel_overview.setLayout(new BorderLayout(0, 0));
		final JScrollPane scrollPane1 = new JScrollPane();
		panel_overview.add(scrollPane1, BorderLayout.CENTER);
		txtpnModpackInfo = new JEditorPane();
		txtpnModpackInfo.setContentType("text/html");
		txtpnModpackInfo.setEditable(false);
		txtpnModpackInfo.setText("<html>\r\n  <head>\r\n    \r\n  </head>\r\n  <body>\r\n    <p style=\"margin-top: 0\">\r\n      Loading modpack info-page...\r\n    </p>\r\n  </body>\r\n</html>\r\n");
		scrollPane1.setViewportView(txtpnModpackInfo);
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return panel_overview;
	}

}
